version: "3.9"

services: 
  bento:
    image: joshuabrown42/bento:latest
    volumes:
      # Append Bento config location to below line.
      - ./bento/config.js:/usr/share/nginx/html/config.js
    ports:
      # Replace host port 80 (left side) with desired port.
      - 80:80